---
title: "Plot of Winter Arctic Sea Ice"
date: "March 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r warning=FALSE,message=FALSE}
library(ggplot2)
library(readr)
library(lubridate)
library(dplyr)
```

```{r message=FALSE, warning=FALSE}
setwd("../../conner/daily_plots/")

ice_df <- read_csv("sea_ice/N_seaice_extent_daily_v3.0.csv")
```

```{r warning=FALSE}
## format and clean data

# modify variable class
ice_df$Extent <- as.numeric(ice_df$Extent)

# remove irrelevant variables
ice_df <- ice_df[2:nrow(ice_df), -c(5, 6)]

# remove partial year 1978, partial data
ice_df <- subset(ice_df, Year != "1978")

# subset for winter months
ice_df <- subset(ice_df, Month %in% c("01", "02", "03", "04", "05"))
```

```{r}
## format month/day dates for plotting years in same plot frame

# combine month and day into string 
full_dates <- with(ice_df, paste0(Month, "/", Day, "/", Year))
full_dates <- mdy(full_dates)
mnth_day <- format(full_dates, format="%m-%d")

# add month/day to df
ice_df <- cbind(ice_df, mnth_day)

# add mean extension of ice by year
ice_df$annual_mean <- ave(ice_df$Extent, ice_df$Year)

# get max extension of ice by year
maxes <- ice_df %>%
         group_by(Year) %>%
         slice(which.max(Extent))
         
```


```{r}
# define color palette
brks <- seq(from=90, to=40, length.out = 40)
palt <- sapply(brks, function(x){hcl(h=180, c=0, l=x)})

```


```{r, fig.align="center", fig.height=5, fig.width=8}
ggplot()+
  geom_line(data=subset(ice_df, Year != "2018"),
            aes(x=mnth_day, y=Extent, color=Year, group=Year), 
            size=1, show.legend = TRUE) +
  geom_line(data=subset(ice_df, Year == "2018"), 
            aes(x=mnth_day, y=Extent, group=Year), 
            size=1.25, color="black", lineend="square", 
            show.legend = FALSE) +
  scale_color_manual(values=palt, guide=FALSE) +
  geom_point(data=maxes, aes(x=mnth_day, y=Extent),
             color="grey50", size= 3) +
  geom_point(data=maxes, aes(x=mnth_day, y=Extent, color=Year),
             size= 2) +
  geom_point(data=subset(maxes, Year==2018),
             aes(x=mnth_day, y=Extent),
             color="black", size= 2) +
  geom_text(data=subset(maxes, Year %in% c("1979", "2018")),
            aes(x=mnth_day, y=Extent, label=Year),
            nudge_x = 3.5, nudge_y = 0.175)+
  labs(title="Extent of Artic Winter Sea Ice by Year",
       y="Millions of Square Kilometers",
       x="") +
  scale_x_discrete(breaks=c("01-01", "02-01", "03-01", "04-01", "05-01", "05-30"),
                   labels=c("Jan", "Feb", "Mar", "Apr", "May", "June"))+
  scale_y_continuous(breaks=c(12, 14, 16)) +
  theme(plot.title = element_text(hjust = 0.5, size=20),
        plot.background = element_blank(),
        panel.background = element_blank(),
        panel.grid = element_blank())

```

